#cloud-config
apt:
  preserve_sources_list: true
  sources:
    microsoft:
      source: "deb https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
      keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF

packages:
  - apt-transport-https
  - dotnet-sdk-2.2
  - git

write_files:
  - encoding: text/plain
    content: |
      [Unit]
      Description=Main Silo
      After=multi-user.target

      [Service]
      Type=idle
      WorkingDirectory=/root/heterogenous-silo
      ExecStart=/usr/bin/dotnet /root/heterogenous-silo/src/Silo/bin/Release/netcoreapp2.2/Silo.dll

      [Install]
      WantedBy=multi-user.target
    owner: root:root
    permissions: '0644'
    path: /etc/systemd/system/main-silo.service

runcmd:
  - [mkdir, /root/heterogenous-silo]
  - [git, clone, "https://github.com/Frank-Krick/heterogenous-orleans", /root/heterogenous-silo]
  - "HOME=/root dotnet build -c Release /root/heterogenous-silo/src/Silo/Silo.csproj"
